### ISSUE TITLE
Item descriptions are lumped into a single paragraph.

### ISSUE THREAD

**Issue by nagoshiashumari** [MantarayAR/octolot#10]
Users can't skip lines in the text, text shows up as a single chunk of text.

Steps to reproduce:
1. Click to edit an item.
2. Enter some text.
3. Hit enter a few times.
4. Enter some more text.
5. Save. Text is shows as a single paragraph.

**Comment by idmontie** [comment]
I'll add a markdown parser or something.

**Comment by idmontie** [comment]
No longer actively being worked on.
